name: djamo_monorepo

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- "flutter analyze"
    description: Run analyzer in all packages

  format:
    run: melos exec -- "flutter format ."
    description: Run dart formatter in all packages

  test:
    run: melos exec --dir-exists="test" -- "flutter test"
    description: Run tests in all packages with test directory

  build_runner:
    run: melos exec -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Run build_runner in all packages

  generate_flutter_gen:
    run: melos exec --depends-on="flutter_gen_runner" -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Generate code with flutter_gen

  clean:
    run: melos exec -- "flutter clean"
    description: Clean all packages