name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
#  analytics_core:
#    path: ../analytics_core
#  analytics_hub:
#    path: ../analytics_hub
  app_ui:
    path: ../app_ui
  auto_route: 9.2.2
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
#  chef_conductor:
#    path: ../conductor
  collection: ^1.18.0
#  crashlytics_tower:
#    path: ../crashlytics_tower
  dart_date: ^1.4.0
  dartz: ^0.10.1
  di:
    path: ../di
  dio: ^5.7.0
  domain:
    path: ../domain
  equatable: ^2.0.5
  firebase_performance_dio: ^0.7.1

  flutter_bloc: ^8.1.6
  flutter_cached_pdfview: ^0.4.2
  flutter_secure_storage: ^9.2.4
  formz: ^0.7.0
  fresh_dio: ^0.4.2
  geolocator: ^13.0.2
  get_it: ^7.6.4
  http_certificate_pinning: ^2.1.3
  http_parser: ^4.0.2
  hydrated_bloc: ^9.1.5
  injectable: ^2.5.0
  internet_connection_checker: ^3.0.1
  mask_text_input_formatter: ^2.9.0
  meta: ^1.15.0
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  petit_extension:
    path: ../petit_extension
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  rxdart: ^0.27.7
  share_plus: ^10.0.2
  synchronized: ^3.3.0+3
  url_launcher: ^6.3.0
#  usecases_core:
#    path: ../usecases_core
  vibration: ^3.1.3
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  auto_route_generator: 9.0.0
  build_runner: 2.4.12
  injectable_generator: 2.6.2
  mocktail: 1.0.4
  retrofit_generator: ^9.1.2
  very_good_analysis: 6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
