name: app_ui
description: The Truth
version: 0.1.6
publish_to: none

environment:
  sdk: 3.5.3
  flutter: 3.24.3

dependencies:
  animate_do: ^3.3.4
  badges: ^3.1.2
#  cached_network_image: ^3.3.1
  countup: ^0.1.4
  currency_text_input_formatter: ^2.2.3
  dart_date: ^1.4.0
  dartx: ^1.2.0
  dots_indicator: ^4.0.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
#  flutter_cache_manager: ^3.3.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_signature_pad: ^3.0.1
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html_core: ^0.15.2
  gap: ^3.0.1
  grouped_list: ^6.0.0
  intl: 0.19.0
  lottie: ^3.1.0
  mask_text_input_formatter: ^2.9.0
  meta: ^1.11.0
  petit_extension:
    path: ../petit_extension
  pinput: ^4.0.0
  pretty_qr_code: ^3.3.0
  shimmer: ^3.0.0
  very_good_infinite_list: ^0.9.0

dev_dependencies:
  flutter_gen: ^5.4.0
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  very_good_analysis: 6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    # Fonts
    - assets/fonts/
    # SVG
    - assets/icons/
    #Animations
    - assets/animations/
    #Images
    - assets/illustrations/
    - assets/images/
    #brands
    - assets/brands/
    #bank_logos
    - assets/bank_logos/
    #Tests: for temporary use
    - assets/djamo_icons/
    #widgetbook: for temporary use
    - assets/widget_book/
  fonts:
    - family: GTWalsheimPro
      fonts:
        - asset: assets/fonts/GTWalsheimPro-Bold.ttf
          weight: 800
        - asset: assets/fonts/GTWalsheimPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/GTWalsheimPro-Bold.ttf
          weight: 600
        - asset: assets/fonts/GTWalsheimPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/GTWalsheimPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/GTWalsheimPro-Thin.ttf
          weight: 300
    - family: OCRAStd
      fonts:
        - asset: assets/fonts/OCRAStd.otf

flutter_gen:
  output: lib/src/tokens/assets
  assets:
    outputs:
      package_parameter_enabled: true
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true
