name: app_ui
description: "Shared UI component for djamo-monorepo"
version: 0.0.1

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  code:
    path: ../code

  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.0
  flutter_gen_runner: ^5.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    # Fonts
    - assets/fonts/
    # SVG
    - assets/icons/
    #Animations
    - assets/animations/
    #Images
    - assets/illustrations/
    - assets/images/
    #brands
    - assets/brands/
    #bank_logos
    - assets/bank_logos/
    #Tests: for temporary use
    - assets/djamo_icons/
    #widgetbook: for temporary use
    - assets/widget_book/
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: GTWalsheimPro
      fonts:
        - asset: assets/fonts/GTWalsheimPro-Bold.ttf
          weight: 800
        - asset: assets/fonts/GTWalsheimPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/GTWalsheimPro-Bold.ttf
          weight: 600
        - asset: assets/fonts/GTWalsheimPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/GTWalsheimPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/GTWalsheimPro-Thin.ttf
          weight: 300
    - family: OCRAStd
      fonts:
        - asset: assets/fonts/OCRAStd.otf
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
flutter_gen:
  output: lib/src/tokens/assets
  assets:
    outputs:
      package_parameter_enabled: true
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true
