name: domain
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_mappr_annotation: ^2.2.0
  collection: ^1.18.0
  dartx: ^1.2.0
  di:
    path: ../di
  diacritic: ^0.1.6
  equatable: ^2.0.5
  injectable: ^2.5.0
  intl: 0.19.0
  mask_text_input_formatter: ^2.9.0
  meta: ^1.11.0
  petit_extension:
    path: ../petit_extension
  phone_numbers_parser: ^9.0.3
  rxdart: ^0.27.7
  uuid: ^4.5.1
  base32: ^2.1.3
  crypto: ^3.0.6
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_mappr: ^2.5.0
  build_runner: 2.4.12
  injectable_generator: 2.6.2
  mocktail: 1.0.4
  test: ^1.0.0
  very_good_analysis: 6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
